{% set name = "node-semver" %}
{% set version = "0.9.1" %}
{% set sha256 = "f052dbdcbc42dd5a0c04b22829a3af98c1f29e4675cc6d88db24250a3f7f8ec7" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - nodesemver

about:
  home: https://github.com/podhmo/python-semver
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: port of node-semver
  dev_url: https://github.com/podhmo/python-semver

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
